# Generated by Django 4.2.4 on 2023-12-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_reserva_recepcionista_cliente_alter_reserva_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('recepcionista', 'Recepcionista'), ('personalaseo', 'PersonalAseo'), ('administrador', 'Administrador')], default='recepcionista', max_length=15),
        ),
    ]
