# Generated by Django 4.2.4 on 2023-12-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_cliente_usuario_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='camas',
            new_name='ocupacion',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='cama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
