# Generated by Django 4.2.4 on 2023-12-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_habitacion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.IntegerField(default=30000),
        ),
    ]
