# Generated by Django 4.2.4 on 2023-12-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_habitacion_numero_alter_habitacion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite'), ('deluxe', 'Deluxe')], max_length=15),
        ),
    ]
