# Generated by Django 4.2.4 on 2023-12-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_habitacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='ocupacion',
            field=models.IntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres')], default=1),
        ),
    ]
