# Generated by Django 4.2.4 on 2023-12-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_habitacion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
