# Generated by Django 4.2.4 on 2023-12-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='jornada',
            field=models.CharField(choices=[('duirno', 'Duirno'), ('vespertino', 'Vespertino'), ('mixta', 'Mixta')], default='duirno', max_length=10),
        ),
    ]
