# Generated by Django 4.2.4 on 2023-12-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_usuario_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
